hydra:
  run:
    dir: ./

train_file: ../ccks2022/ccks_nl2sql/sub_train.json
dev_file: ../ccks2022/ccks_nl2sql/sub_dev.json
test_file: ../ccks2022/ccks_nl2sql/dev.json

# Model
model:
  _target_: models.mt5.MT5ForSeq2SeqAndSeqClassification.from_pretrained
  num_labels: 3
  tokenizer: ${model_name_or_path}

# Data loading
read_tensor:
  _target_: data.seq2seq.read_data_with_table_column_names_simplify
  db_info_path: ../ccks2022/ccks_nl2sql/db_info.json
  top_k_table_names: 5
  top_k_col: all
  max_input_length: 512  # max sequence length is 494
  max_output_length: 128  # max output length is 98

extended_vocab:

# Data collator
collator:
  _target_: data.collators.MetaCollator

# Dataloader
num_workers: 4
prefetch_factor: 2

# Wiki path pretrain v8.2
model_name_or_path: ../pretrained-models/mt5-xl
pretrain:

output_dir: experiments/nl2sql.mt5.xl.w_cls.table_name_cn_bm25.top${read_tensor.top_k_table_names}.col_en_${read_tensor.top_k_col}.v1.0.w1.A100.s${seed}


do_train: True
evaluate_during_training: True

do_eval: True
eval_sub_path:

# Training hyper-parameters
per_gpu_train_batch_size: 4
per_gpu_eval_batch_size: 4
learning_rate: 1e-4
gradient_accumulation_steps: 2
weight_decay: 0.01
adam_epsilon: 1e-6
adam_betas: "(0.9, 0.999)"
max_grad_norm: 0.0
num_train_epochs: 50
max_steps: 0
warmup_proportion: 0.1
warmup_steps: 0

optimizer: "adafactor"

logging_steps: 5
save_steps: -1
save_best: True
ddp_eval: False
eval_steps: 1000
no_cuda: False
seed: 42
local_rank: -1
fp16: True
fp16_opt_level: O1
fp16_bfloat16: True

# Prediction config
prediction_cfg:
  metric: "cls_em"
  measure: 1
  best_checkpoint:
  best_result:

generator: True
max_output_length: 128
num_beams: 1
num_return_sequences: 1
post_process:
  _target_: general_util.metrics.SQLResultsWCls

# fairscale.FullyShardedDP
fairscale_config:
  _target_: general_util.fsdp_utils.default_initialize
  fp16: ${fp16}
  reshard_after_forward: False
  move_grads_to_cpu: False
  move_params_to_cpu: False

# Deepspeed config
ds_cfg:
  train_micro_batch_size_per_gpu: ${per_gpu_train_batch_size}
  gradient_accumulation_steps: ${gradient_accumulation_steps}
  optimizer:
    type: AdamW
    params:
      lr: ${learning_rate}
      betas: [0.9, 0.999]
      eps: ${adam_epsilon}
      weight_decay: ${weight_decay}
  scheduler:
    type: WarmupDecayLR
    params:
      total_num_steps:
      warmup_max_lr: ${learning_rate}
      warmup_num_steps:
      warmup_type: linear
  gradient_clipping: ${max_grad_norm}
  fp16:
    enabled: ${fp16}
    initial_scale_power: 12
  zero_optimization:
    stage: 3
#    offload_optimizer:
#      device: cpu
#      pin_memory: True
#    offload_param:
#      device: cpu
#      pin_memory: True
#  activation_checkpointing:
#    partition_activations: True
#    cpu_checkpointing: True
#    contiguous_memory_optimization: False
#    number_checkpoints: False
#    synchronize_checkpoint_boundary: False
#    profile: False
  steps_per_print: 1024

summary_helper:
  _target_: general_util.tensorboard_helper.SummaryWriterHelper
  batch_index_or_keys:
  outputs_index_or_keys:

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:
world_size:
